### PR TITLE
Rails 6.1 Compatability

### PR DESCRIPTION
**Pull request by walski**
This allows working with Rails 6.1 RC1.

### CODE REVIEW

**Comment by walski** [comment]
We're using this in production, now.

**Comment by shellixyz** [comment]
I can confirm this PR is working fine for me with Rails 6.1

**Comment by sposin** [comment]
Is there a particular reason this hasn't been merged?

**Comment by travisofthenorth** [comment]
@zachaysan you mind taking a look at this? Blocking 6.1 upgrade for us.

**Comment by zachaysan** [comment]
@travisofthenorth, @walski and everyone else: I'm very sorry, I was hospitalized and in otherwise poor health for months and this slipped. I'll merge and cut a gem for this now. Thank you very much for bringing it to my attention.

**Comment by zachaysan** [comment]
@travisofthenorth I've pushed the gem to rubygems, let me know if you have any trouble.

https://rubygems.org/gems/activerecord-hierarchical_query/versions/1.3.0

**Comment by travisofthenorth** [comment]
@zachaysan no worries. Thank you so much for the quick turnaround!

**Comment by zachaysan** [comment]
@travisofthenorth it's the least I could do. 

I should investigate getting another maintainer in the event that this happens again, as my medical condition, while fine for now, could reappear. If you or @walski have any interest let me know.

**Pull request merged**
