### PR TITLE
Add Union Distinct Functionality

### PR DESCRIPTION
**Pull request by nickfarina**
Reopening this PR that includes the method for rails versions < 4.2, please let me know if you'd rather go about contributing in a different way.

### CODE REVIEW

**Comment by nickfarina** [comment]
Weren't the travis failures due to not including a method for the older rails versions?

**Comment by take-five** [comment]
I've fixed this error myself :) Your code is merged to master

**Comment by take-five** [comment]
Thanks for contribution!

**Comment by take-five** [comment]
Check out version 0.1.1 from rubygems.org
And thanks again for contribution! :)

**Comment by nickfarina** [comment]
Great! 👍

**Pull request closed without merging**
